version: '3.8'

networks:
  petnet:
    driver: ${APP_NETWORK_DRIVER}

services:
  postgres:
    platform: ${PLATFORM}
    image: ${POSTGRES_IMAGE}
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_ACCESSKEY}
      - POSTGRES_PASSWORD=${POSTGRES_SECRET}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - petnet
  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./volumes/redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    networks:
      - petnet
